In [3]:
# default_exp algo.dl.pytorch

%reload_ext autoreload
%autoreload 2

In [ ]:
algo_dl_pytorch

# pytorch


PyTorch是由Facebook的人工智能部门开发的机器学习和深度学习工具，用于处理大规模图像分析，包括对象检测，分割和分类。 但是，它不限于这些任务。 它可以与其他框架一起使用来实现复杂的算法。 它是使用Python和C ++语言编写的。 要在GPU环境中处理大规模计算，应相应地修改编程语言。 PyTorch提供了一个很好的框架来编写自动在GPU环境中运行的函数。--《PyTorch Recipes-A Problem-Solution Approach》2019

PyTorch是一个Python软件包，提供两个高级功能：

     具有强大GPU加速功能的Tensor计算（如NumPy）

     基于基于磁带的autograd系统构建的深度神经网络

您可以在需要时重用自己喜欢的Python软件包（例如NumPy，SciPy和Cython）来扩展PyTorch。

https://pytorch.org/

https://github.com/pytorch/pytorch

https://pytorch.org/tutorials/

In [7]:
# !pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple

!pip freeze | grep torch

torch==1.5.0
torchtext==0.2.3
torchvision==0.4.2


In [8]:
import torch

In [11]:
torch.version.__version__

'1.5.0'

# Using Tensors

In [8]:
x = [12, 34, 35, 89, 58]

In [9]:
torch.is_tensor(x)

False

In [10]:
torch.is_storage(x)

False

## create an object that contains random numbers from Torch
similar to NumPy library

In [11]:
y = torch.randn(1, 2, 3, 4, 5)

In [12]:
torch.is_tensor(y)

True

In [13]:
torch.is_storage(y)

False

### Returns the total number of elements in the :attr:`input` tensor.

In [14]:
torch.numel(y)

120

The y object is a tensor; however, it is not stored. To check the total number of elements in the input tensor object, the numerical element function can be used. The following script is another example of creating zero values in a 2D tensor and counting the numerical elements in it.

### 0 tensor

In [15]:
torch.zeros(4, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 基于ndarray生成tensor

In [16]:
import numpy as np

In [17]:
torch.from_numpy(np.array(x))

tensor([12, 34, 35, 89, 58])

# Probability Distributions Using PyTorch

## Sampling Tensors

### Problem
Weight initialization is an important task in training a neural network and any kind of deep learning model, such as a convolutional neural network (CNN), a deep neural network (DNN), and a recurrent neural network (RNN). The question always remains on how to initialize the weights.

In [20]:
torch.manual_seed(14)
torch.randn(4, 4)

tensor([[-0.3418, -0.0956,  1.3965,  0.7791],
        [-1.1795,  0.2456, -0.3493,  0.1234],
        [ 1.2525, -0.0177,  1.8372, -1.4072],
        [ 1.4651, -1.6924,  0.0423,  0.5466]])

### Variable Tensors

In [21]:
from torch.autograd import Variable

In [22]:
Variable(torch.ones(2,2), requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

# nb_export

In [2]:
from nbdev.export import *
notebook2script()

Converted 00_core.ipynb.
Converted 00_template.ipynb.
Converted active_learning.ipynb.
Converted algo_dl_keras.ipynb.
Converted algo_ml_eda.ipynb.
Converted algo_ml_tree_catboost.ipynb.
Converted algo_ml_tree_lgb.ipynb.
Converted algo_rs_associated_rules.ipynb.
Converted algo_rs_match_deepmatch.ipynb.
Converted algo_rs_matrix.ipynb.
Converted algo_rs_search_vector_faiss.ipynb.
Converted algo_seq_embeding.ipynb.
Converted algo_seq_features_extraction_text.ipynb.
Converted datastructure_dict_list_set.ipynb.
Converted datastructure_matrix_sparse.ipynb.
Converted engineering_concurrency.ipynb.
Converted engineering_nbdev.ipynb.
Converted engineering_panel.ipynb.
Converted engineering_snorkel.ipynb.
Converted index.ipynb.
Converted math_func_basic.ipynb.
Converted math_func_loss.ipynb.
Converted operating_system_command.ipynb.
Converted plot.ipynb.
Converted utils_functools.ipynb.
Converted utils_json.ipynb.
Converted utils_pickle.ipynb.
Converted utils_time.ipynb.


In [7]:
!nbdev_build_docs

No notebooks were modified
converting /Users/luoyonggui/PycharmProjects/nbdevlib/index.ipynb to README.md
