In [3]:
# default_exp algo.ml.models

%reload_ext autoreload
%autoreload 2

In [40]:
import numpy as np

import pandas as pd
from sklearn.model_selection import KFold

# data

In [3]:
x, y = (np.array([[70, 64,  5,  1,  1],
        [60, 63,  9,  1,  1],
        [70, 65, 11,  1,  1],
        [40, 69, 10,  1,  1],
        [40, 63, 58,  1,  1],
        [70, 48,  9,  1,  1],
        [70, 48, 11,  1,  1],
        [80, 63,  4,  2,  1],
        [60, 63, 14,  2,  1],
        [30, 53,  4,  2,  1],
        [80, 43, 12,  2,  1],
        [40, 55,  2,  2,  1],
        [60, 66, 25,  2,  1],
        [40, 67, 23,  2,  1],
        [20, 61, 19,  3,  1],
        [50, 63,  4,  3,  1],
        [50, 66, 16,  0,  1],
        [40, 68, 12,  0,  1],
        [80, 41, 12,  0,  1],
        [70, 53,  8,  0,  1],
        [60, 37, 13,  1,  1],
        [90, 54, 12,  1,  0],
        [50, 52,  8,  1,  0],
        [70, 50,  7,  1,  0],
        [20, 65, 21,  1,  0],
        [80, 52, 28,  1,  0],
        [60, 70, 13,  1,  0],
        [50, 40, 13,  1,  0],
        [70, 36, 22,  2,  0],
        [40, 44, 36,  2,  0],
        [30, 54,  9,  2,  0],
        [30, 59, 87,  2,  0],
        [40, 69,  5,  3,  0],
        [60, 50, 22,  3,  0],
        [80, 62,  4,  3,  0],
        [70, 68, 15,  0,  0],
        [30, 39,  4,  0,  0],
        [60, 49, 11,  0,  0],
        [80, 64, 10,  0,  0],
        [70, 67, 18,  0,  0]]),
 np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]))

# algo-ml-models

模型的调用汇总

## LogisticRegression

In [4]:
def lr_module(x, y, mode='sklearn'):
    if mode == 'sklearn':
        from sklearn.linear_model import LogisticRegression as LR
        lr = LR() #建立逻辑回归模型
        lr.fit(x, y) #用筛选后的特征数据来训练模型
        accrucy = lr.score(x, y)
    elif mode == 'stats':
        import statsmodels.api as sm

        lr = sm.Logit(y, x)
        lr = logrB.fit(disp=0)

        accrucy = (pd.Series(lr.predict(x)).map(round)==pd.Series(y)).mean()
    print(u'逻辑回归模型训练结束。')
    print(u'模型的平均正确率为：%s' % accrucy)

In [5]:
lr_module(x, y)

逻辑回归模型训练结束。
模型的平均正确率为：0.875


In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [9]:
def knn_module(X_train:pd.DataFrame, y, X_test:pd.DataFrame, c_param, bdry=None):
    knn=KNeighborsClassifier(n_neighbors=c_param)
    knn.fit(X_train.values, y.values)
    y_pred = knn.predict(X_test.values)
    return y_pred

In [10]:
y_pred = knn_module(pd.DataFrame(x), pd.Series(y).to_frame(), pd.DataFrame(x), 3)

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
(y_pred==y).mean()

0.875

In [22]:
def svm_rbf_module(X_train:pd.DataFrame, y, X_test:pd.DataFrame, c_param=1, bdry= 0.5):
    svm_rbf = SVC(C=c_param, probability=True)
    svm_rbf.fit(X_train.values, y.values)
    y_pred = svm_rbf.predict_proba(X_test.values)[:,1] >= bdry
    return y_pred

In [23]:
y_pred = svm_rbf_module(pd.DataFrame(x), pd.Series(y).to_frame(), pd.DataFrame(x))

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [24]:
y_pred

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [25]:
(y_pred==y).mean()

0.8

In [26]:
def svm_poly_module(X_train:pd.DataFrame, y, X_test:pd.DataFrame, c_param=(1, 3), bdry= 0.5):
    svm_poly=SVC(C=c_param[0], kernel='poly', degree= c_param[1], probability=True)
    svm_poly.fit(X_train.values, y.values)
    pred = svm_poly.predict_proba(X_test.values)[:,1] >= bdry
    return pred

In [27]:
y_pred = svm_poly_module(pd.DataFrame(x), pd.Series(y).to_frame(), pd.DataFrame(x))

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [28]:
y_pred

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [29]:
(y_pred==y).mean()

0.8

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
def lr_module(X_train:pd.DataFrame, y, X_test:pd.DataFrame, c_param=1, bdry= 0.5):
    # penalty惩罚系数
    lr = LogisticRegression(C=c_param,penalty='l2')
    lr.fit(X_train.values, y.values)
    pred= lr.predict_proba(X_test.values)[:,1]>=bdry
    return pred

In [33]:
y_pred = lr_module(pd.DataFrame(x), pd.Series(y).to_frame(), pd.DataFrame(x))

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [34]:
y_pred

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True,  True])

In [35]:
(y_pred==y).mean()

0.875

In [36]:
def rf_module(X_train:pd.DataFrame, y, X_test:pd.DataFrame, c_param=100, bdry= 0.5):
    # 参数设置 https://www.cnblogs.com/harvey888/p/6512312.html
    rf= RandomForestClassifier(n_jobs=-1,n_estimators=c_param, criterion='entropy', max_features= 'auto',
                               max_depth=20,min_samples_split= 3, random_state=0, oob_score =True)
    rf.fit(X_train.values, y.values)
    pred = rf.predict_proba(X_test.values)[:,1]>=bdry
    return pred

In [37]:
y_pred = rf_module(pd.DataFrame(x), pd.Series(y).to_frame(), pd.DataFrame(x))

/Users/luoyonggui/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


In [38]:
y_pred

array([ True, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True, False,  True,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True])

In [39]:
(y_pred==y).mean()

1.0

In [ ]:
def models_train_val(models, trainset, valset=None, num_folds=5, folds_use=1):
    """
    
    :models: list. 'lr rf'.split()
    :trainset: tuple. (X_train, y_train)
    :valset: tuple. (X_val, y_val)
    """
    fold=KFold(num_folds,shuffle=True, random_state=14)

In [1]:
#export


In [ ]:
from nbdev.export import notebook2script
notebook2script('.ipynb')