In [3]:
# default_exp data.structure.numpy

%reload_ext autoreload
%autoreload 2

# numpy
https://numpy.org/

User Guide https://numpy.org/doc/stable/user/index.html

## install
一般使用Anaconda自带

In [1]:
!pip freeze | grep numpy

numpy==1.17.0
numpydoc==0.8.0


# import numpy

In [2]:
import numpy as np

# ndarray(array)
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

In [16]:
a = np.array([(1.5,2,3), (4,5,6)])

## attrs

In [17]:
a.ndim  # the number of axes (dimensions) of the array.

2

In [18]:
a.shape

(2, 3)

In [19]:
a.size  # the total number of elements of the array. This is equal to the product of the elements of shape.

6

In [20]:
a.dtype

dtype('float64')

ndarray.itemsize：每个element所占的字节数。the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [21]:
a.itemsize  # 

8

ndarray.data：包含数组实际元素的缓冲区。 通常，我们不需要使用此属性，因为我们将使用索引工具访问数组中的元素

In [22]:
a.data

# Array Creation

## from list

In [7]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
np.array( [ [1,2], [3,4] ], dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### to list

In [8]:
a.tolist()

[2, 3, 4]

## 标准的array
By default, the dtype of the created array is float64.

In [10]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

### eye单位矩阵

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.eye(3, M=5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### diag只有对角线上有元素的矩

In [27]:
np.diag([2, 6, 3])

array([[2, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

### buildFromFunction

In [44]:
np.fromfunction(lambda i,j: i+j, shape=(2, 3))

array([[0., 1., 2.],
       [1., 2., 3.]])

### 随机数填充的矩阵

#### [0, 1)均匀分布

In [30]:
np.random.rand(2, 3)

array([[0.655557  , 0.65903332, 0.65996999],
       [0.16087678, 0.07359523, 0.6661718 ]])

In [36]:
np.random.random((2, 3))

array([[0.19230652, 0.58237661, 0.13920882],
       [0.98213761, 0.65351736, 0.15617274]])

#### 标准正态分布

In [31]:
np.random.randn(2, 3)

array([[ 0.19991434, -0.65105904, -0.07307731],
       [-1.38931621,  1.51679815, -0.0516504 ]])

In [38]:
np.random.normal(loc=0, scale=1, size=(2, 3))

array([[ 0.29398565,  0.26853925,  1.36371783],
       [-1.14327918,  1.98972488,  0.74267586]])

#### 指定随机种子

In [45]:
np.random.RandomState(seed=14).rand(2, 3)

array([[0.51394334, 0.77316505, 0.87042769],
       [0.00804695, 0.30973593, 0.95760374]])

In [46]:
np.random.RandomState(seed=14).rand(2, 3)

array([[0.51394334, 0.77316505, 0.87042769],
       [0.00804695, 0.30973593, 0.95760374]])

## create sequences of numbers instead of list

### 产生指定间隔的seq

In [13]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [14]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### 产生指定数量的等间隔的seq

In [15]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

# Universal Functions
https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

NumPy提供熟悉的数学函数，例如sin，cos和exp。 在NumPy中，这些称为“通用函数”（ufunc）。 在NumPy中，这些函数在数组上逐个元素操作，生成数组作为输出。

In [31]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

# Statistics Functions
https://numpy.org/doc/stable/reference/routines.statistics.html

## numpy.percentile
Compute the q-th percentile of the data along the specified axis.

Returns the q-th percentile(s) of the array elements.

In [28]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [29]:
np.percentile(a, 50)  # 中位数，如果元素数量为偶数，则返回中间两个元素的均值

3.5

In [30]:
np.median(a)

3.5