In [3]:
# default_exp data-structure.pandas

%reload_ext autoreload
%autoreload 2

# pandas
pandas有两种数据结构Series & DataFrame
* Series  
很强大，完全可以代替list和dict
* DataFrame  
    * 可以看做是具有相同index的Series的组合
    * 也可以看做是index+columns+array(2d)
    
## api
https://pandas.pydata.org/pandas-docs/stable/reference/index.html

## install
一般情况下，不用自己安装，使用Anaconda自带的就好

In [1]:
!pip freeze | grep pandas

pandas==0.25.3
pandas-datareader==0.7.0
pandas-summary==0.0.7
sklearn-pandas==1.8.0


## import pandas

In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 100)  # 设置显示数据的最大列数，防止出现省略号…，导致数据显示不全
pd.set_option('expand_frame_repr', False)  # 当列太多时不自动换行

# pd.set_option('display.max_rows', None)  # 显示所有行

# or
# pd.options.display.max_colwidth = 200
# pd.options.display.max_columns = 100

# ignore pandas's warnings 
# import warnings
# warnings.filterwarnings('ignore')

# gen Series

In [4]:
s = pd.Series()

s.loc[0] = 1.1
s.loc[1] = 2
s.loc['name'] = 'ian'
s

0       1.1
1         2
name    ian
dtype: object

## from list

In [5]:
list1 = [1.1, 2, 3, None, 4, 5, 4, '2010-04-14']
s = pd.Series(list1)
s

0           1.1
1             2
2             3
3          None
4             4
5             5
6             4
7    2010-04-14
dtype: object

### Series转换为list

In [6]:
s.to_list()

[1.1, 2, 3, None, 4, 5, 4, '2010-04-14']

In [7]:
s.tolist()

[1.1, 2, 3, None, 4, 5, 4, '2010-04-14']

## from array

### 基于1D ndarray

In [8]:
s = pd.Series(np.arange(5))
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

#### Series转换为1d ndarray

In [11]:
s.values

array([0, 1, 2, 3, 4])

### from 2d array

In [10]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
s = pd.Series(arr.tolist())
s

0    [0, 1, 2]
1    [3, 4, 5]
dtype: object

In [11]:
# 直接转会报错
pd.Series(arr)

Exception: Data must be 1-dimensional

#### Series to 2d array

In [18]:
# right way
np.array(s.values.tolist())

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
# wrong
s.values

array([list([0, 1, 2]), list([3, 4, 5])], dtype=object)

In [15]:
# wrong
s.map(np.array).values

array([array([0, 1, 2]), array([3, 4, 5])], dtype=object)

## from dict

In [22]:
d = {'s': 0, 'b': 1, 'm': 4, 'e': 2}
s = pd.Series(d)
s

s    0
b    1
m    4
e    2
dtype: int64

### Series转换为dict

In [13]:
s.to_dict()

{'s': 0, 'b': 0, 'm': 0, 'e': 0}

## Series转换为DataFrame

In [6]:
s.to_frame('aaa')

aaa
s    0
b    0
m    0
e    0

In [3]:
s.to_frame()

0
s  0
b  0
m  0
e  0

In [4]:
s.name = 'tt'

In [5]:
s.to_frame()

tt
s   0
b   0
m   0
e   0

# Series Attributes

In [23]:
s

s    0
b    1
m    4
e    2
dtype: int64

In [24]:
s.dtype

dtype('int64')

In [25]:
s.dtypes

dtype('int64')

In [26]:
s.ndim

1

In [27]:
s.shape

(4,)

In [28]:
s.size

4

In [29]:
s.count()  # Return number of non-NA/null observations in the Series.

4

In [30]:
s.name

In [31]:
s.empty

False

# gen DataFrame

## from list

In [32]:
df = pd.DataFrame([[0, 0], [0, 1], [1, 1]], columns=['x', 'y'])
df

x  y
0  0  0
1  0  1
2  1  1

### df转换为list

In [34]:
df.values.tolist()

[[0, 0], [0, 1], [1, 1]]

## 基于2D ndarray

In [35]:
dfff = pd.DataFrame(np.random.randn(6, 4), index=list('一二三四五六'), columns=list('ABCD'))
dfff

A         B         C         D
一  0.362785  0.446433 -0.319947 -0.389018
二  0.231044 -0.384697 -1.268299 -0.590938
三  0.720519 -0.492162  1.397541  0.889715
四  0.205160 -0.432107  2.259447  1.161909
五 -0.329641  0.213463 -0.001954 -1.108646
六 -0.465088  0.952484 -0.510075 -0.660350

### df转换为ndarray

In [28]:
dfff.values

array([[ 0.89776061,  0.35692832, -1.25445924, -0.5164656 ],
       [-0.92992327,  0.0208218 , -0.57000273,  1.06255045],
       [-0.80926389, -0.12887038, -1.05143452, -0.83414592],
       [-1.56125762,  1.46108812,  0.18152318,  0.47601516],
       [ 1.58779899,  0.42360879, -1.56623493,  1.40040837],
       [ 0.27610633, -0.31824622,  1.18123137,  0.87166894]])

__注意：原df并不会改变!!!__

## from dict

In [38]:
df2 = pd.DataFrame({'A': [2, 3, 1, 5],
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  2 2013-01-02  1.0  3   test  foo
1  3 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  5 2013-01-02  1.0  3  train  foo

### dict values不是列表的情况

In [40]:
d = {'a':1, 'b':2}

In [3]:
# 直接会报错
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [41]:
# 正确的打开方式
pd.Series(d).to_frame().T

a  b
0  1  2

### df转换为dict

key是columnname，value是Series

In [31]:
dict(df2)

{'A': 0    1.0
 1    1.0
 2    1.0
 3    1.0
 Name: A, dtype: float64, 'B': 0   2013-01-02
 1   2013-01-02
 2   2013-01-02
 3   2013-01-02
 Name: B, dtype: datetime64[ns], 'C': 0    1.0
 1    1.0
 2    1.0
 3    1.0
 Name: C, dtype: float32, 'D': 0    3
 1    3
 2    3
 3    3
 Name: D, dtype: int32, 'E': 0     test
 1    train
 2     test
 3    train
 Name: E, dtype: category
 Categories (2, object): [test, train], 'F': 0    foo
 1    foo
 2    foo
 3    foo
 Name: F, dtype: object}

# DataFrame Attributes

In [45]:
df

x  y
0  0  0
1  0  1
2  1  1

In [42]:
df.dtypes

x    int64
y    int64
dtype: object

In [43]:
df.shape

(3, 2)

In [48]:
len(df) # 行数

3

In [44]:
df.size # 元素的个数

6

In [46]:
df2.empty  # 判断df是否为空

False

In [47]:
df3 = pd.DataFrame()
df3.empty

True

### append

In [16]:
dict(zip(list('ABCD'), list('1234')))

{'A': '1', 'B': '2', 'C': '3', 'D': '4'}

In [29]:
dfff.append([dict(zip(list('ABCD'), list('1234'))),dict(zip(list('ABCD'), list('2789')))], ignore_index=True)

A          B         C         D
0  0.897761   0.356928  -1.25446 -0.516466
1 -0.929923  0.0208218 -0.570003   1.06255
2 -0.809264   -0.12887  -1.05143 -0.834146
3  -1.56126    1.46109  0.181523  0.476015
4    1.5878   0.423609  -1.56623   1.40041
5  0.276106  -0.318246   1.18123  0.871669
6         1          2         3         4
7         2          7         8         9

# group

In [77]:
arr = np.random.randint(100, size=(20,2))
arr

array([[45, 49],
       [73, 87],
       [78, 71],
       [89, 79],
       [94, 95],
       [67, 65],
       [78, 58],
       [ 2, 40],
       [15, 92],
       [40, 13],
       [63, 77],
       [74, 53],
       [60, 55],
       [36, 43],
       [82,  1],
       [ 7, 30],
       [39, 36],
       [86, 48],
       [34,  4],
       [43, 33]])

In [78]:
df = pd.DataFrame(arr, columns='a b'.split())
df.head(2)

a   b
0  45  49
1  73  87

In [79]:
df.a.describe()

count    20.000000
mean     55.250000
std      27.703078
min       2.000000
25%      38.250000
50%      61.500000
75%      78.000000
max      94.000000
Name: a, dtype: float64

## pd.cut & pd.qcut
### pd.cut 
按值进行分组

Bin values into discrete intervals.

Use `cut` when you need to segment and sort data values into bins. This
function is also useful for going from a continuous variable to a
categorical variable. For example, `cut` could convert ages to groups of
age ranges. Supports binning into an equal number of bins, or a
pre-specified array of bins.


### pd.qcut
按照分位数进行分组。先对值进行排序，然后 前20%的一组，20%-80%的一组，剩下的一组

Quantile-based discretization function. Discretize variable into equal-sized buckets based on rank or based on sample quantiles. For example 1000 values for 10 quantiles would produce a Categorical object indicating quantile membership for each data point.

pd.cut(
    x,
    bins,
    right=True,
    labels=None,
    retbins=False,
    precision=3,
    include_lowest=False,
    duplicates='raise',
)

### 将a列的值按等距方式分为5组

In [81]:
pd.cut(df.a, bins=5,precision=2)

0     (38.8, 57.2]
1     (57.2, 75.6]
2     (75.6, 94.0]
3     (75.6, 94.0]
4     (75.6, 94.0]
5     (57.2, 75.6]
6     (75.6, 94.0]
7     (1.91, 20.4]
8     (1.91, 20.4]
9     (38.8, 57.2]
10    (57.2, 75.6]
11    (57.2, 75.6]
12    (57.2, 75.6]
13    (20.4, 38.8]
14    (75.6, 94.0]
15    (1.91, 20.4]
16    (38.8, 57.2]
17    (75.6, 94.0]
18    (20.4, 38.8]
19    (38.8, 57.2]
Name: a, dtype: category
Categories (5, interval[float64]): [(1.91, 20.4] < (20.4, 38.8] < (38.8, 57.2] < (57.2, 75.6] < (75.6, 94.0]]

### 任意指定分组

In [82]:
pd.cut(df.a, bins=[0,23,49,100],precision=2)

0      (23, 49]
1     (49, 100]
2     (49, 100]
3     (49, 100]
4     (49, 100]
5     (49, 100]
6     (49, 100]
7       (0, 23]
8       (0, 23]
9      (23, 49]
10    (49, 100]
11    (49, 100]
12    (49, 100]
13     (23, 49]
14    (49, 100]
15      (0, 23]
16     (23, 49]
17    (49, 100]
18     (23, 49]
19     (23, 49]
Name: a, dtype: category
Categories (3, interval[int64]): [(0, 23] < (23, 49] < (49, 100]]

In [83]:
# 按照分位数等距分组
pd.qcut(df.a, 5,precision=2)

0     (44.2, 69.4]
1     (69.4, 78.8]
2     (69.4, 78.8]
3     (78.8, 94.0]
4     (78.8, 94.0]
5     (44.2, 69.4]
6     (69.4, 78.8]
7     (1.99, 35.6]
8     (1.99, 35.6]
9     (35.6, 44.2]
10    (44.2, 69.4]
11    (69.4, 78.8]
12    (44.2, 69.4]
13    (35.6, 44.2]
14    (78.8, 94.0]
15    (1.99, 35.6]
16    (35.6, 44.2]
17    (78.8, 94.0]
18    (1.99, 35.6]
19    (35.6, 44.2]
Name: a, dtype: category
Categories (5, interval[float64]): [(1.99, 35.6] < (35.6, 44.2] < (44.2, 69.4] < (69.4, 78.8] < (78.8, 94.0]]

In [84]:
pd.qcut(df.a, 5,precision=2).value_counts()

(78.8, 94.0]    4
(69.4, 78.8]    4
(44.2, 69.4]    4
(35.6, 44.2]    4
(1.99, 35.6]    4
Name: a, dtype: int64

In [85]:
pd.qcut(df.a, [0, .25, .5, .75, 1.],precision=2)

0     (38.25, 61.5]
1      (61.5, 78.0]
2      (61.5, 78.0]
3      (78.0, 94.0]
4      (78.0, 94.0]
5      (61.5, 78.0]
6      (61.5, 78.0]
7     (1.99, 38.25]
8     (1.99, 38.25]
9     (38.25, 61.5]
10     (61.5, 78.0]
11     (61.5, 78.0]
12    (38.25, 61.5]
13    (1.99, 38.25]
14     (78.0, 94.0]
15    (1.99, 38.25]
16    (38.25, 61.5]
17     (78.0, 94.0]
18    (1.99, 38.25]
19    (38.25, 61.5]
Name: a, dtype: category
Categories (4, interval[float64]): [(1.99, 38.25] < (38.25, 61.5] < (61.5, 78.0] < (78.0, 94.0]]

In [86]:
# 如果存在相等的值时，可以能会导致分配不均匀
pd.qcut(df.a, [0, .25, .5, .75, 1.],precision=2).value_counts()

(61.5, 78.0]     6
(38.25, 61.5]    5
(1.99, 38.25]    5
(78.0, 94.0]     4
Name: a, dtype: int64

# groupby

## GroupBy objects
https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html

GroupBy objects are returned by groupby calls: pandas.DataFrame.groupby(), pandas.Series.groupby(), etc.

In [87]:
df = pd.DataFrame({'收据号': [1, 1, 2, 3, 3, 3],
                   '项目名称': ['挂号费', '药费', '挂号费', '挂号费', '治疗费', '床位费'],
                   '费用': [1, 2, 3, 4, 5, 6],
                   'claim': [4, 4, 4, 5, 5, 5]})
df

收据号 项目名称  费用  claim
0    1  挂号费   1      4
1    1   药费   2      4
2    2  挂号费   3      4
3    3  挂号费   4      5
4    3  治疗费   5      5
5    3  床位费   6      5

In [88]:
dfg = df.groupby('项目名称')
dfg

可以看到，dfg类似generator，是可以迭代的。每一项是一个元组，元组有两个元素，i[0]是分组的值，i[1]对应的是这个分组下的子DataFrame

In [92]:
for i in dfg:
    print(type(i))
    print(i)
    print(type(i[1]))
    break

<class 'tuple'>
('床位费',    收据号 项目名称  费用  claim
5    3  床位费   6      5)
<class 'pandas.core.frame.DataFrame'>


### Attrs

In [93]:
dfg.groups  # 包含 分组值 及 对应的 df的索引

{'床位费': Int64Index([5], dtype='int64'),
 '挂号费': Int64Index([0, 2, 3], dtype='int64'),
 '治疗费': Int64Index([4], dtype='int64'),
 '药费': Int64Index([1], dtype='int64')}

In [94]:
dfg.indices

{'床位费': array([5]),
 '挂号费': array([0, 2, 3]),
 '治疗费': array([4]),
 '药费': array([1])}

In [95]:
dfg.get_group('床位费')

收据号 项目名称  费用  claim
5    3  床位费   6      5

## apply
Apply function func group-wise and combine the results together.

是否按组聚合，取决于应用的func是否为聚合函数

In [96]:
dfg.apply(sum)  # 对数值型的column的值进行相加

收据号       项目名称  费用  claim
项目名称                           
床位费     3        床位费   6      5
挂号费     6  挂号费挂号费挂号费   8     13
治疗费     3        治疗费   5      5
药费      1         药费   2      4

In [99]:
dfg['费用'].apply(lambda x: (x-x.mean()))

0   -1.666667
1    0.000000
2    0.333333
3    1.333333
4    0.000000
5    0.000000
Name: 费用, dtype: float64

In [100]:
dfg['费用'].apply(lambda x: (x-x.mean())/x.std())  # 分组进行标准化

0   -1.091089
1         NaN
2    0.218218
3    0.872872
4         NaN
5         NaN
Name: 费用, dtype: float64

## agg
这里的func必须为聚合函数

func : function, str, list or dict

    Function to use for aggregating the data. If a function, must either
    work when passed a DataFrame or when passed to DataFrame.apply.

    Accepted combinations are:

    - function
    - string function name
    - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
    - dict of axis labels -> functions, function names or list of such.

In [ ]:
dfg.agg(func)

## groupby+聚合函数

### sum, mean, median, nunique

In [101]:
df.groupby('收据号')['费用'].sum()  # equal to df.groupby('收据号')['费用'].agg(sum) or df.groupby('收据号')['费用'].agg('sum')


收据号
1     3
2     3
3    15
Name: 费用, dtype: int64

In [102]:
df.groupby('收据号')['费用'].mean()

收据号
1    1.5
2    3.0
3    5.0
Name: 费用, dtype: float64

In [103]:
df.groupby('收据号')['费用'].median()

收据号
1    1.5
2    3.0
3    5.0
Name: 费用, dtype: float64

In [104]:
df.groupby('收据号')['费用'].nunique()

收据号
1    2
2    1
3    3
Name: 费用, dtype: int64

### 自定义聚合函数

In [2]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [4]:
df.groupby('收据号')['费用'].agg(peak_to_peak)

收据号
1    1
2    0
3    2
Name: 费用, dtype: int64

### 多个列应用相同的聚合函数

In [160]:
df.groupby('收据号')['费用', 'claim'].sum()

费用  claim
收据号           
1     3      8
2     3      4
3    15     15

### 一个列应用多个聚合函数

In [165]:
df.groupby('收据号')['费用'].agg(['sum', 'mean', 'max', peak_to_peak])

sum  mean  max  peak_to_peak
收据号                              
1      3   1.5    2             1
2      3   3.0    3             0
3     15   5.0    6             2

### 多个列应用多个聚合函数

In [44]:
gg = df.groupby('收据号')[['费用', 'claim']].agg(['sum', 'mean', 'max'])
gg

费用          claim         
    sum mean max   sum mean max
收据号                            
1     3  1.5   2     8    4   4
2     3  3.0   3     4    4   4
3    15  5.0   6    15    5   5

In [45]:
gg[('费用', 'sum')]

收据号
1     3
2     3
3    15
Name: (费用, sum), dtype: int64

### 最佳实践

In [113]:
def aggregate_features(df_, cols, agg_func, prefix=''):
    df = df_.copy()
    agg_df = df.groupby(cols).agg(agg_func)
    agg_df.columns = [prefix + '_'.join(col).strip() for col in agg_df.columns.values]
    return agg_df

In [114]:
agg_func = {
    '收据号':  ['count','nunique'],
    '费用':  ['nunique'],
    'claim':  ['mean','max','min','std'],
} 

In [115]:
agg_df = aggregate_features(df, ['项目名称'], agg_func)

In [116]:
agg_df

收据号_count  收据号_nunique  费用_nunique  claim_mean  claim_max  claim_min  claim_std
项目名称                                                                                 
床位费           1            1           1    5.000000          5          5        NaN
挂号费           3            3           3    4.333333          5          4    0.57735
治疗费           1            1           1    5.000000          5          5        NaN
药费            1            1           1    4.000000          4          4        NaN

## groupby+非聚合函数

### cumsum()

In [13]:
df.groupby('项目名称')['费用'].cumsum()

0    1
1    2
2    4
3    8
4    5
5    6
Name: 费用, dtype: int64

### shift
按照不同的类别进行shift, pandas太强大！

In [16]:
df['项目名称_费用_shift1'] = df.groupby('项目名称')['费用'].shift(1)

In [17]:
df

收据号 项目名称  费用  claim  项目名称_费用_shift1
0    1  挂号费   1      4             NaN
1    1   药费   2      4             NaN
2    2  挂号费   3      4             1.0
3    3  挂号费   4      5             3.0
4    3  治疗费   5      5             NaN
5    3  床位费   6      5             NaN

### rolling

In [23]:
df.groupby('项目名称')['费用'].rolling(2).sum().reset_index('项目名称', drop=True)

5    NaN
0    NaN
2    4.0
3    7.0
4    NaN
1    NaN
Name: 费用, dtype: float64

In [24]:
df['项目名称_费用_rolling2'] = df.groupby('项目名称')['费用'].rolling(2).sum().reset_index('项目名称', drop=True)

In [25]:
df

收据号 项目名称  费用  claim  项目名称_费用_shift1  项目名称_费用_rolling2
0    1  挂号费   1      4             NaN               NaN
1    1   药费   2      4             NaN               NaN
2    2  挂号费   3      4             1.0               4.0
3    3  挂号费   4      5             3.0               7.0
4    3  治疗费   5      5             NaN               NaN
5    3  床位费   6      5             NaN               NaN

In [10]:
df

收据号 项目名称  费用  claim
0    1  挂号费   1      4
1    1   药费   2      4
2    2  挂号费   3      4
3    3  挂号费   4      5
4    3  治疗费   5      5
5    3  床位费   6      5

### expanding

In [15]:
df['项目名称_费用_expanding1'] = df.groupby('项目名称')['费用'].expanding(1).sum().reset_index('项目名称', drop=True)

In [16]:
df

收据号 项目名称  费用  claim  项目名称_费用_expanding1
0    1  挂号费   1      4                 1.0
1    1   药费   2      4                 2.0
2    2  挂号费   3      4                 4.0
3    3  挂号费   4      5                 8.0
4    3  治疗费   5      5                 5.0
5    3  床位费   6      5                 6.0

### rank

In [25]:
df.groupby('项目名称')['费用'].rank()

0    1.0
1    1.0
2    2.0
3    3.0
4    1.0
5    1.0
Name: 费用, dtype: float64